<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="22032" started-at="2019-02-10T07:23:36Z" finished-at="2019-02-10T07:23:58Z">
    <groups>
    </groups>
    <test name="FirstTest" duration-ms="160" started-at="2019-02-10T07:23:36Z" finished-at="2019-02-10T07:23:37Z">
      <class name="gitMaster.GitMasterTest">
        <test-method status="FAIL" signature="logintest()[pri:0, instance:gitMaster.GitMasterTest@7ce6a65d]" name="logintest" duration-ms="30" started-at="2019-02-10T07:23:37Z" finished-at="2019-02-10T07:23:37Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at gitMaster.GitMasterTest.logintest(GitMasterTest.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
      </class> <!-- gitMaster.GitMasterTest -->
    </test> <!-- FirstTest -->
    <test name="SecondTest" duration-ms="11784" started-at="2019-02-10T07:23:37Z" finished-at="2019-02-10T07:23:49Z">
      <class name="secondTest.SecondTest">
        <test-method status="PASS" signature="loginsecondtest()[pri:0, instance:secondTest.SecondTest@612679d6]" name="loginsecondtest" duration-ms="11783" started-at="2019-02-10T07:23:37Z" finished-at="2019-02-10T07:23:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginsecondtest -->
      </class> <!-- secondTest.SecondTest -->
    </test> <!-- SecondTest -->
    <test name="ThirdTest" duration-ms="9518" started-at="2019-02-10T07:23:49Z" finished-at="2019-02-10T07:23:58Z">
      <class name="thirdTest.ThirdTest">
        <test-method status="PASS" signature="logintest()[pri:0, instance:thirdTest.ThirdTest@69b0fd6f]" name="logintest" duration-ms="9514" started-at="2019-02-10T07:23:49Z" finished-at="2019-02-10T07:23:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
      </class> <!-- thirdTest.ThirdTest -->
    </test> <!-- ThirdTest -->
  </suite> <!-- Suite -->
</testng-results>
